$pdf_mode = 1;

$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';

# Use BibTeX (default)
$bibtex_use = 1;  # optional, could omit entirely

# Output directories still enabled if you had them
$out_dir = 'outputs';
$aux_dir = 'outputs';
